### ISSUE TITLE
data error

### ISSUE THREAD

**Issue by doriongilmore** [Mokhet/MFF-roster-tracker#35]
I'll edit this issue with errors I notice

- Missing T2
   - Loki 
   - Angela 

- Satana registered as villain instead of hero

**Comment by doriongilmore** [comment]
Hi, very nice upgrade for the uniforms ! And thanks for adding my idea, it's much simpler to set gears options.
Once I get used to your scripts, I'll try to help you with new issues

**Comment by Mokhet** [comment]
Thanks for reporting those issues. Please add new issues instead of editing this one. I will fix data in a few minutes.

**Comment by Mokhet** [comment]
Fix has been silently pushed to live tool and is added to next 2.3.0 version. Thanks again.
