### ISSUE TITLE
About setting all gears options in one click

### ISSUE THREAD

**Issue by doriongilmore** [Mokhet/MFF-roster-tracker#36]
Hi, very nice upgrade for the uniforms ! And thanks for adding my idea, it's much simpler to set gears options. Also, there is a **visual** bug : the min max and average values don't refresh.

Once I get used to your scripts, I'll try to help you with new issues.

**Comment by Mokhet** [comment]
You are welcome.

I think the refresh bug is fixed in next 2.3.0 version (available in beta version). I'll keep this issue open until I release 2.3.0 to be sure I have correctly fixed it.

**Comment by doriongilmore** [comment]
I just noticed something else :
I switched character to refresh these values and the non-checked gears options go back to the "set all value"

Example for the 3rd gear, if I set all gears options to HP, then set the first two to HP/lvl, check only one of these two options, then switch character to refresh values, the non-checked HP/lvl option go back to HP

**Comment by Mokhet** [comment]
Currently the "checked" state is not used by the "Set all ..." feature.

The test is "if the current stat is the same as the set all state, don't change anything".

Do you think I should change the selected option only if the checkbox is not checked ?

**Comment by Mokhet** [comment]
I have two options :

1) Current one : Change only if the stat is different from the "Set all ..." choose.

2) Could be : Change only if the checked state is false

Which one (or another I don't think about) do you think I should do ?

**Comment by Mokhet** [comment]
Third option (option 1 and option 2) : 

Change if checkbox is not checked and stat is different from the "Set all ..." chosen.

**Comment by doriongilmore** [comment]
Sorry if I explain badly, English is not my native language.
If think it's fine as it is :  Change only if the stat is different from the "Set all ..." choose.

But after setting all options in one click (like HP), if I change one (to HP/lvl) and don't check the box (because I didn't have the value or something else), then I refresh the character (by switching to another) the unchecked option (HP/lvl) will go back to the set all option (HP).

Like if this set all option was verified each time you come back to the character ?

**Comment by doriongilmore** [comment]
I confirm the set all option is verified each time you come back to the character, and is priority :
If you set manually your options, don't check the boxes, and come back to the character, the options become blanks again

**Comment by Mokhet** [comment]
Ahhh ok, sorry English is not my native language either :) I think I got you point now, and I think I fixed it. It is available for test in the 2.3.0 beta version. https://www.mokhet.com/MFF-beta/

However, I have added another option. You can now choose between "Set all to ..." and "Set all unchecked to ..."
