### ISSUE TITLE
Unable to remove gears

### ISSUE THREAD

**Issue by dcmc87** [Mokhet/MFF-roster-tracker#37]
After using the "Set all to..." dropdown option in the gears page, options for that gear can no longer be set back to being blank. If you do this for all 4 gears, the character is stuck in a T2 ready state forever.

By the way, is your in game name mokhet as well? I came across your site randomly on Reddit, and realised we might coincidentally be in the same alliance - my IGN is Skyyeblu.

Also, I cobbled together an Android app which allows you to select screenshots of the gears and character detail pages from MFF and uses OCR to process them into valid JSON compatible with your website's character import : https://github.com/dcmc87/MFFRosterParser . If you're using Android and want to test it you could build it yourself or I could send you the APK.

It could probably be pretty easily translated to a web version for parsing uploaded screenshots, unfortunately I'm not familiar enough with webdev to do that.

**Comment by Mokhet** [comment]
Hello, the bug is fixed. I was not saving the data when the option for the gear was empty. Don't know why I did that :) It is available in the version 2.3.0 in the beta folder.

I checked and yes we are in the same alliance :D

The OCR android app is amazing, congratz. I am adding a link to your project in the readme file. That is incredible. I could not imagine something so sweet, that's very nice.

I am on iOs, but would you mind if I check if I can understand the java part and eventually translate it to a web version ?

**Comment by dcmc87** [comment]
Yup sure go ahead, but you might want to wait for me to tidy up the code a
bit so it's readable haha. The concept is pretty simple if you remove the
UI code and another chunk I used to parse part of the marvelfuturefight
website.

It's built around the tesseract library, and there are a few issues :

1. It depends on OCR accuracy to match gear names to the database, so a
mistake or difference in formatting could break that part

2. OCR rectangle pixel dimensions have to be hardcoded for different aspect
ratios, but I think 16:9/16:10/4:3 are the most common anyway

3. Tesseract accuracy is pretty affected by pre-processing of images and
the font MFF uses, had to do quite a bit of specific color tweaking
(compression formats may break it) & bitmap scaling (slowing it down a lot)
to get it to work reasonably reliably.

I may try to port it to plain Java myself too, I'm trying to pick up the
basics of web backend stuff myself so this is an interesting project =)

**Comment by Mokhet** [comment]
I'll wait :)

But once again, amazing idea !
