### ISSUE TITLE
Impossible d'enregistrer les modification

### ISSUE THREAD

**Issue by vcro** [Mokhet/MFF-roster-tracker#54]
Bonjour,

Je n'arrive plus a enregistrer les modifications que j'apporte a mes personnages, 

Lorsque je change les statistiques de mes personnage (les nouveau personnage que je n'ai pas encore mis)
les modifications ne sont pas enregistrer.

cordialement.VCRO

**Comment by Mokhet** [comment]
Je viens de reproduire le problème pour les valeurs de "gears" sur Agent Venom. Je regarde immédiatement ce que j'ai fait comme bêtise.

**Comment by Mokhet** [comment]
Fixed. Je ne sais pas pourquoi mais j'avais oublié un flag sur false permettant d'autoriser/ignorer l'enregistrement des valeurs. Du coup il était toujours en mode "ignorer", donc pas d'enregistrement. Je suis désolé de ne pas avoir vu ça.
